package ibarodf.core;

public enum Command {
    DISPLAY_HELP,
    DISPLAY_THE_META_DATA_A_FILE,

    
    
    //Operations on ODF file
    DISPLAY_THE_META_DATA_OF_AN_ODF_FILE,
    CHANGE_THE_TITLE_OF_AN_ODF_FILE, //ok
    CHANGE_THE_SUBJECT_OF_AN_ODF_FILE, //ok
    ADD_A_KEYWORD_TO_AN_ODF_FILE, //ok
    REPLACE_KEYWORDS_TO_AN_ODF_FILE,
    CHANGE_THE_COMMENTS_OF_AN_ODF_FILE, //ok
    CHANGE_THE_CREATOR_OF_AN_ODF_FILE,
    REPLACE_THE_DESCRIPTION_OF_AN_ODF_FILE,
    //Operation directory
    DISPLAY_THE_META_DATA_OF_ODF_FILES_IN_A_DIRECTORY

}   
